### PR TITLE
Convert project to TypeScript

### LINKED ISSUE #131: Refactor/document Leopard source code as TypeScript
See a recent comment: https://github.com/leopard-js/leopard/pull/119#discussion_r922909462

> Incorrect method name. Errors when using `this.touching("edge")` while a speech bubble is active.
> 
> (I got very lucky! My test project happened to include this case. We could consider using Typescript to avoid these kinds of errors and also to provide type hints for people using Leopard.)

See also discussion in #128—since we're already working with a build step, it wouldn't add any new steps to the current development workflow.

Bonus reason for writing Leopard in TypeScript: [sb-edit uses TypeScript](https://github.com/leopard-js/sb-edit/tree/master/src), and it's good to be consistent across the two connected codebases!

### PR DESCRIPTION
**Pull request by adroitwhiz**
Resolves #131

~~There's a lot left to do here--for instance, class visibility modifiers and making the API signatures explicit--but I'm opening this as a draft PR for feedback + any contributions.~~

EDIT: Let's punt on figuring out method visibility and API surface for now.

### CODE REVIEW

**Comment by adroitwhiz** [comment]
@PullJosh @towerofnix This PR is ready for review now!

File: src/Project.ts [hunk 1]
```diff
@@ -100,37 +121,38 @@ export default class Project {
...
-          throw new Error(`Unimplemented trigger ${trigger.trigger}`);
+          throw new Error(`Unimplemented trigger ${String(trigger.trigger)}`);
       }
 
       // Default to false
-      const prevPredicate = !!this._prevStepTriggerPredicates.get(trigger);
-      this._prevStepTriggerPredicates.set(trigger, predicate);
+      const prevPredicate =
+        !!this._prevStepTriggerPredicates.get(triggerWithTarget);
+      this._prevStepTriggerPredicates.set(triggerWithTarget, predicate);
```
Comment (towerofnix) [inline src/Project.ts:144]: Is this a runtime/behavioral change? It looks like the value of `prevPredicate` would evaluate differently here, but I'm not versed in edge-activated triggers to be certain. If it's behavioral, should this change be a separate bug fix pull request?

File: src/Project.ts [hunk 2]
```diff
@@ -146,32 +168,34 @@ export default class Project {
...
+  public fireTrigger(trigger: symbol, options?: TriggerOptions): Promise<void> {
     // Special trigger behaviors
     if (trigger === Trigger.GREEN_FLAG) {
       this.restartTimer();
       this.stopAllSounds();
       this.runningTriggers = [];
 
       for (const spriteName in this.sprites) {
-        const sprite = this.sprites[spriteName];
+        const sprite = this.sprites[spriteName]!;
```
Comment (towerofnix) [inline src/Project.ts:198]: I'm pretty sure the `!` is only necessary here since `sprites` is a `Partial`. If `sprites` is rewritten without partial, this is probably safe to remove.

File: src/Project.ts [hunk 3]
```diff
@@ -207,21 +232,25 @@ export default class Project {
       triggers.map(({ trigger, target }) => {
         return trigger.start(target);
       })
-    );
+    ).then();
```
Comment (towerofnix) [inline src/Project.ts:235]: This is really weird. I get it, but can we do an async function instead?

Also unnecessary `() => { return x }` pattern above.

File: src/Project.ts [hunk 4]
```diff
@@ -207,21 +232,25 @@ export default class Project {
...
-  get spritesAndClones() {
+  public get spritesAndClones(): Sprite[] {
     return Object.values(this.sprites)
-      .flatMap(sprite => sprite.andClones())
+      .flatMap((sprite) => sprite!.andClones())
       .sort((a, b) => a._layerOrder - b._layerOrder);
   }
 
-  get spritesAndStage() {
+  public get spritesAndStage(): [...Sprite[], Stage] {
```
Comment (towerofnix) [inline src/Project.ts:244]: Is there an advantage to writing this this way instead of `(Sprite | Stage)[]`? What you have *feels* more descriptive, but if TypeScript isn't actually learning anything more from it (e.g. that there is always exactly one `Stage` in the array or that the `Stage` is always the last element) I think we should use the more generic description.

**Review by towerofnix — CHANGES_REQUESTED** [review]
I left a shorter review covering just the files through `src/Project.ts`. This is looking awesome! Just a few comments. I'll get to the remaining files later, just taking a break for the morning now and figure you can use what I've got so far. 📦 

Another thing I wanted to note is that you've got some very specific style things going on here, e.g. parentheses around single-argument arrow functions, and commas following the last item in array/object literals. Are these being formatted or verified automatically? I didn't see any `"scripts"` in package.json doing so but might have missed it.

I think this PR would be an OK time to implement an auto-format script with `prettier` (explicitly configured how you're using it — sb-edit doesn't follow these rules I commented on). But feel free to disagree with me on that and save it for a following PR!

File: src/Project.ts [hunk 5]
```diff
@@ -1,11 +1,30 @@
...
+
+type TriggerWithTarget = {
+  target: Sprite | Stage;
+  trigger: Trigger;
+};
 
 export default class Project {
-  constructor(stage, sprites = {}, { frameRate = 30 } = {}) {
+  public stage: Stage;
+  public sprites: Partial<Record<string, Sprite>>;
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Project.ts:15]: `Record<string, T>` assumes that *every* string key maps to a valid `T`. When we access a sprite from `Project.sprites` by name, that sprite may not exist.

Unlike `sb-edit`, I enabled TypeScript's strict mode here, so it's stricter about checking for null and undefined values, and I wanted to make use of that by making sure that we don't assume object keys always map to a value.

It might be better to have `Project` take a type parameter listing the valid sprite names, so that we can statically know whether or not a sprite exists and error only if the user tries to access a nonexistent sprite.

File: src/Input.ts [hunk 6]
```diff
@@ -1,5 +1,19 @@
...
+  private _stage: Stage;
+  private _canvas: HTMLCanvasElement;
+  private _onKeyDown: (key: string) => unknown;
+
+  public mouse: Mouse;
+  public keys: string[];
+  public constructor(
+    stage: Input["_stage"],
+    canvas: Input["_canvas"],
+    onKeyDown: Input["_onKeyDown"]
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Input.ts:15]: IIRC it was down to the length of the type names. I can change it to be consistent across constructors.

File: src/Project.ts [hunk 7]
```diff
@@ -1,11 +1,30 @@
...
+  public renderer: Renderer;
+  public input: Input;
+
+  private loudnessHandler: LoudnessHandler;
+  private _cachedLoudness: number | null;
+
+  public runningTriggers: TriggerWithTarget[];
+  private _prevStepTriggerPredicates: WeakMap<TriggerWithTarget, boolean>;
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Project.ts:23]: Good catch! I'll do so when possible.

File: src/Project.ts (hunk 1 above)
Comment (adroitwhiz) [reply src/Project.ts:144]: Looks like I introduced a bug; good catch!

File: src/Project.ts (hunk 4 above)
Comment (adroitwhiz) [reply src/Project.ts:244]: I'll change the signature

File: src/Project.ts (hunk 3 above)
Comment (adroitwhiz) [reply src/Project.ts:235]: Changed to an async function

File: src/Project.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (towerofnix) [reply src/Project.ts:15]: Got it, that makes sense. Do you feel it'd be worth enabling strict mode in sb-edit (once we're done with this PR) and being more conscious of undefined/null there?

That static erroring sounds practical from a user's perspective. I haven't dug into the code for targets yet, but is it possible to get the same effect for variables (i.e. error when accessing nonexistant variables)? Maybe that's something we're already doing and/or free.

File: src/Input.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (towerofnix) [reply src/Input.ts:16]: I think that would make sense, avoiding duplicating type definitions sounds like it'd save some headache down the line & ensure a more consistent style across class definitions.

File: src/Project.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Project.ts:15]: Yes; either after or as part of the sb-edit TypeScript upgrade, I plan on enabling strict mode and fixing any resulting errors there.

I've already done something similar for sprites' variables here. I ran into an issue when trying to do it for `Project`, though--if I make the project's sprites a type parameter, the `Project` constructor can't have a default value for the sprites argument ([it's complicated](https://stackoverflow.com/questions/56505560/how-to-fix-ts2322-could-be-instantiated-with-a-different-subtype-of-constraint)).

[the remark this answers is not in the document]
Comment (towerofnix) [reply src/Project.ts:15]: Got it, thanks for the reference info!

File: src/Project.ts (hunk 2 above)
Comment (towerofnix) [reply src/Project.ts:201]: As discussed we're using `Partial<Record>` which justifies the need for a "this definitely isn't null" assertion here.

File: src/Input.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Input.ts]: It turns out you can also infer class member types from the constructor--I just did that instead.

File: src/Costume.ts [hunk 8]
```diff
@@ -1,5 +1,12 @@
 export default class Costume {
-  constructor(name, url, center = { x: 0, y: 0 }) {
+  public name: string;
+  public url: string;
+  public img: HTMLImageElement;
+  public isBitmap: boolean;
```
Comment (towerofnix) [inline src/Costume.ts:5]: Not an issue for this PR but let's revisit this `isBitmap` flag when dejankifying/reworking costume loading.

File: src/Sprite.ts [hunk 9]
```diff
@@ -406,40 +501,39 @@ export class Sprite extends SpriteBase {
...
     };
   }
 
-  createClone() {
+  public createClone(): void {
     const clone = Object.assign(
-      Object.create(Object.getPrototypeOf(this)),
+      Object.create(Object.getPrototypeOf(this) as object) as Sprite,
       this
     );
```
Comment (towerofnix) [inline src/Sprite.ts:512]: I get it, but this feels like a distinctly ES5-ism. Is it possible to explicitly provide the necessary configuration options through to a normally constructed new `Sprite` instance? I feel like this risks sharing actual objects (like `effects`) if we aren't careful.

As far as I can tell `Object.create` doesn't even call the class constructor (just creating an object whose internal prototype is the provided prototype). It feels really weird to me to "construct" a new instance in a way which bypasses the stated constructor.

```js
class Foo { field = 32; constructor() { this.value = 123; } }

foo = Object.create(Foo.prototype);
console.log(foo.field, foo.value);

foo2 = new Foo();
console.log(foo2.field, foo2.value);

foo3 = Object.create(Object.getPrototypeOf(foo2), Object.getOwnPropertyDescriptors(foo2));
console.log(foo3.field, foo3.value);
```

I'll branch this off into its own issue since it probably takes some investigation (and deciding if it's worth it), and isn't really relevant to this PR, just wanted to give you a heads up on it since the odd look of the code itself is a little exacerbated with TypeScript.

File: src/Sprite.ts [hunk 10]
```diff
@@ -450,37 +544,38 @@ export class Sprite extends SpriteBase {
...
     this._project.runningTriggers = this._project.runningTriggers.filter(
       ({ target }) => target !== this
     );
   }
 
-  andClones() {
-    return [this, ...this.clones.flatMap(clone => clone.andClones())];
+  // TODO: is this necessary now that the clone hierarchy seems to be flattened?
+  public andClones(): Sprite[] {
+    return [this, ...this.clones.flatMap((clone) => clone.andClones())];
```
Comment (towerofnix) [inline src/Sprite.ts:567]: I don't think this is necessary, and I've flattened many arrays in my recent years 📦

File: src/Sprite.ts [hunk 11]
```diff
@@ -521,26 +616,43 @@ export class Sprite extends SpriteBase {
...
       yield;
     } while (t < 1);
   }
 
-  get penDown() {
+  public moveAhead(value = Infinity): void {
+    if (typeof value === "number") {
+      this._project.changeSpriteLayer(this, value);
+    } else {
+      this._project.changeSpriteLayer(this, 1, value);
```
Comment (towerofnix) [inline src/Sprite.ts:639]: Can we make the type for `value` explicit here and below? It matches the `number` or third argument for `Project.changeSpriteLayer` which, oh god, also isn't typed, wut. (It's from `spritesAndClones[number]` which is `Sprite`.)

File: src/Sprite.ts [hunk 12]
```diff
@@ -552,33 +664,36 @@ export class Sprite extends SpriteBase {
...
   }
 
-  stamp() {
+  public stamp(): void {
     this._project.renderer.stamp(this);
   }
 
-  touching(target, fast = false) {
+  public touching(
+    target: "mouse" | "edge" | Sprite | Stage,
```
Comment (towerofnix) [inline src/Sprite.ts:686]: Out of scope for this PR (since it's sb-edit changes) but I think this is one of the only places we're still using "keywords" like this without an enum.

File: src/Sprite.ts [hunk 13]
```diff
@@ -635,77 +753,88 @@ export class Sprite extends SpriteBase {
...
+    if (this._speechBubble?.timeout) clearTimeout(this._speechBubble.timeout);
 
+    const speechBubble: SpeechBubble = { text, style: "say", timeout: null };
     let done = false;
-    const timeout = setTimeout(() => {
-      this._speechBubble.text = "";
-      this.timeout = null;
+    const timeout = window.setTimeout(() => {
+      speechBubble.text = "";
+      speechBubble.timeout = null;
```
Comment (towerofnix) [inline src/Sprite.ts:773]: Why not clear `this._speechBubble` here entirely? If we're trying to preserve an object value, why not make `_speechBubble` non-undefined and skip the `?.` optional chaining in methods above?

File: src/Sprite.ts [hunk 14]
```diff
@@ -635,77 +753,88 @@ export class Sprite extends SpriteBase {
...
       height: {
         value: initialConditions.height || 360,
-        enumerable: true
-      }
+        enumerable: true,
+      },
     });
 
-    this.name = "Stage";
-
```
Comment (towerofnix) [inline src/Sprite.ts:701]: This is just unused code, right? I don't see references to `SpriteBase.name` anywhere else in this file or sb-edit's Leopard serialization code.

File: src/renderer/Skin.ts [hunk 15]
```diff
@@ -1,25 +1,37 @@
...
+    this.width = 0;
+    this.height = 0;
   }
 
   // Get the skin's texture for a given (screen-space) scale.
-  /* eslint-disable-next-line no-unused-vars */
-  getTexture(scale) {
-    return null;
-  }
+  public abstract getTexture(scale: number): WebGLTexture | null;
```
Comment (towerofnix) [inline src/renderer/Skin.ts:17]: This is kinda abstract (pun not intended), can we include an example value for `scale` here just to tell what scale it's on (pun not intended) and a clear-cut case for its usage?

File: src/renderer/SpeechBubbleSkin.ts [hunk 16]
```diff
@@ -24,27 +39,32 @@ export default class SpeechBubbleSkin extends Skin {
...
-  _restyleCanvas() {
-    const ctx = this._canvas.getContext("2d");
+  private _restyleCanvas(): void {
+    const ctx = this._ctx;
     ctx.font = "16px sans-serif";
     ctx.textBaseline = "hanging";
   }
 
-  set flipped(flipped) {
+  public set flipped(flipped: boolean) {
```
Comment (towerofnix) [inline src/renderer/SpeechBubbleSkin.ts:51]: Recurring theme a bit in this PR, but as usual I don't understand why some property setters get type annotations and others don't - especially these really simple ones where I assumed you're sometimes (but not always?) inferring the type for the value from the type of the property being set to it.

File: src/renderer/SpeechBubbleSkin.ts [hunk 17]
```diff
@@ -24,27 +39,32 @@ export default class SpeechBubbleSkin extends Skin {
...
-    const renderBubbleBackground = (x, y, w, h, r, style) => {
+    const ctx = this._ctx;
+
+    const renderBubbleBackground = (
+      x: number,
+      y: number,
+      w: number,
+      h: number,
+      r: number,
+      style: "say" | "think"
```
Comment (towerofnix) [inline src/renderer/SpeechBubbleSkin.ts:66]: Can we enumalize this, maybe import the bubble style from its definition I think in `Sprite.ts`?

File: src/renderer/Drawable.ts [hunk 18]
```diff
@@ -18,30 +24,44 @@ const determinant = (a, b, c) => {
...
+  private _sprite: Sprite | Stage;
+  private _unset: boolean;
+
+  private _lastX!: Sprite["x"] | undefined;
+  private _lastY!: Sprite["y"] | undefined;
+  private _lastRotation!: Sprite["direction"] | undefined;
+  private _lastRotationStyle!: Sprite["rotationStyle"] | undefined;
+  private _lastSize!: Sprite["size"] | undefined;
+  private _lastCostume!: Sprite["costume"];
+  private _lastCostumeLoaded!: boolean;
```
Comment (towerofnix) [inline src/renderer/Drawable.ts:36]: OK, this block confuses me :) I thought I understood the use of `!` for indicating that even though a variable's type implies it could be null/undefined, it certainly isn't at this point... but here we're explicitly allowing for `undefined` at the same time as we define fields. I'd really appreciate some details on the usage here.

File: src/Watcher.ts [hunk 19]
```diff
@@ -30,9 +77,12 @@ export default class Watcher {
     this.y = y;
     this.width = width;
     this.height = height;
+    this.min = 0;
+    this.max = 100;
+    this.step = 1;
```
Comment (towerofnix) [inline src/Watcher.ts:82]: I am pressing a key to doubt because `this.step` is already set earlier in this constructor and `min` and `max` ought to be passed through here but aren't (standing issue w/ PR, see #161).

File: src/Watcher.ts [hunk 20]
```diff
@@ -82,11 +132,11 @@ export default class Watcher {
 
           const indexElem = document.createElement("div");
           indexElem.classList.add("leopard__watcherListItemIndex");
-          indexElem.innerText = index;
+          indexElem.innerText = String(index);
```
Comment (towerofnix) [inline src/Watcher.ts:135]: W3C spec [indicates](https://webidl.spec.whatwg.org/#es-DOMString) that arbitrary values are always stringified (EMCA `ToString`) for IDL `DOMString`, it shouldn't be necessary for us to stringify these values at all. Haven't checked if TypeScript respects that, though.

File: src/Watcher.ts [hunk 21]
```diff
@@ -108,7 +158,8 @@ export default class Watcher {
 
     // Set slider value
     if (this._style === "slider") {
-      this._dom.slider.value = value;
+      // TODO: handle non-numeric slider values
+      this._dom.slider.value = String(value);
```
Comment (towerofnix) [inline src/Watcher.ts:162]: Can we file an issue for this?

**Review by towerofnix — CHANGES_REQUESTED** [review]
This is really awesome work! I've left a bunch of comments throughout, with a number of questions, since I'm still relatively new to TypeScript, and some notes to file issues for new TODO's. Most of my remarks are tidbits/small-scale — on the whole this pull request is great, and really improves the legibility and reliability of Leopard code. Thank you!

File: src/Watcher.ts (hunk 20 above)
Comment (adroitwhiz) [reply src/Watcher.ts:135]: Typescript currently [does not](https://github.com/microsoft/TypeScript/issues/43662) :(

Comment (towerofnix) [reply src/Watcher.ts:135]: Too bad! Good to know.

File: src/Renderer.ts [hunk 22]
```diff
@@ -86,10 +124,9 @@ export default class Renderer {
   }
 
   // Retrieve a given object (e.g. costume or speech bubble)'s skin. If it doesn't exist, make one.
-  _getSkin(obj) {
-    if (this._skins.has(obj)) {
-      return this._skins.get(obj);
-    }
+  public _getSkin(obj: object): Skin {
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:127]: Clarified the type signature.

File: src/Renderer.ts [hunk 23]
```diff
@@ -101,17 +138,17 @@ export default class Renderer {
...
     this._skins.set(obj, skin);
     return skin;
   }
 
   // Retrieve the renderer-specific data object for a given sprite or clone. If it doesn't exist, make one.
-  _getDrawable(sprite) {
-    if (this._drawables.has(sprite)) {
-      return this._drawables.get(sprite);
-    }
+  public _getDrawable(sprite: Sprite | Stage): Drawable {
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:148]: Every method in the renderer that takes a `Sprite | Stage` has a parameter named `sprite`. Changing that would be best left for a future PR--there are a lot of them.

File: src/Renderer.ts [hunk 24]
```diff
@@ -176,7 +224,7 @@ export default class Renderer {
     return framebufferInfo;
   }
 
-  _setShader(shader) {
+  public _setShader(shader: Shader): boolean {
     if (shader !== this._currentShader) {
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:228]: Swapped the if/else

File: src/Renderer.ts [hunk 25]
```diff
@@ -223,37 +271,40 @@ export default class Renderer {
...
+    layers?: Set<Sprite | Stage | PenSkin>,
+    optionsIn: {
+      filter?: (layer: Sprite | Stage | PenSkin) => boolean;
+    } & Partial<RenderSpriteOptions> = {}
+  ): void {
+    const options = {
+      drawMode: ShaderManager.DrawModes.DEFAULT,
+      renderSpeechBubbles: true,
+      ...optionsIn,
+    };
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:298]: > We're only using the `filter` option here

I'm not sure what you mean by this. The function also accesses the `drawMode` option. I could remove the `renderSpeechBubble` de/restructuring though?

File: src/Renderer.ts [hunk 26]
```diff
@@ -223,37 +271,40 @@ export default class Renderer {
...
     // If we're given a filter function in the options, filter by that too.
     // If we're given both, then only include layers which match both.
     const shouldRestrictLayers = layers instanceof Set;
-    const shouldFilterLayers = typeof options.filter === "function";
-    const shouldIncludeLayer = layer =>
+    const shouldIncludeLayer = (layer: Sprite | Stage | PenSkin): boolean =>
       !(
         (shouldRestrictLayers && !layers.has(layer)) ||
-        (shouldFilterLayers && !options.filter(layer))
+        (typeof options.filter === "function" && !options.filter(layer))
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:307]: TypeScript's control flow analysis gets confused and can't "prove" that `shouldFilterLayers` guarantees the type of `options.filter` to be a function.

File: src/Renderer.ts [hunk 27]
```diff
@@ -388,16 +442,16 @@ export default class Renderer {
...
-  ) {
+  private _renderSkin(
+    skin: Skin,
+    drawMode: DrawMode,
+    matrix: MatrixType,
+    scale: number,
+    effects?: _EffectMap,
+    effectMask?: number,
+    colorMask?: [number, number, number, number],
+    spriteColorId?: number
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:453]: I feel like those can provide a false sense of security since TypeScript doesn't actually support nominal typing. I'll create `RGBA`/`RGBANormalized` type aliases for the color tuples anyway.

File: src/Renderer.ts [hunk 28]
```diff
@@ -428,26 +486,24 @@ export default class Renderer {
...
 
     // Used for mapping drawn sprites back to their indices in a list.
     // By looking at the color of a given pixel, we can tell which sprite is
     // the topmost one drawn on that pixel.
-    if (drawMode === ShaderManager.DrawModes.SPRITE_ID) {
-      this.gl.uniform3fv(
-        this._currentShader.uniforms.u_spriteId,
-        idToColor(spriteColorId)
-      );
+    if (drawMode === ShaderManager.DrawModes.SPRITE_ID && spriteColorId) {
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:494]: TypeScript doesn't have static asserts, so we can't statically error.

The other way of doing this would be a discriminated union type (like Rust's `enum`), which TypeScript also doesn't really have.

File: src/Renderer.ts [hunk 29]
```diff
@@ -428,26 +486,24 @@ export default class Renderer {
...
 
     // Actually draw the skin
     this.gl.drawArrays(this.gl.TRIANGLES, 0, 6);
   }
 
-  renderSprite(sprite, options) {
-    const spriteScale = Object.prototype.hasOwnProperty.call(sprite, "size")
-      ? sprite.size / 100
-      : 1;
+  private renderSprite(
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:502]: I'd actually prefer to remove all the underscores once the visibility modifiers are nailed down. Let's leave that to a future PR.

File: src/Renderer.ts [hunk 30]
```diff
@@ -680,14 +756,14 @@ export default class Renderer {
...
-        null,
+        undefined,
+        undefined,
         i
       );
     }
 
-    this._renderLayers(new Set([sprites]), {
-      effectMask: ~effectBitmasks.ghost
+    this._renderLayers(new Set(sprites), {
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:765]: I think it did. If so, the "when sprite clicked" block would be broken.

File: src/Renderer.ts [hunk 31]
```diff
@@ -608,7 +677,11 @@ export default class Renderer {
     return false;
   }
 
-  checkColorCollision(spr, targetsColor, sprColor) {
+  public checkColorCollision(
+    spr: Sprite | Stage,
+    targetsColor: Color,
+    sprColor?: Color
+  ): boolean {
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:684]: It previously errored out because it checked if `!spr.visible` and `Stage` has no `visible` property. I've changed it to work with either.

File: src/Sound.ts [hunk 32]
```diff
@@ -1,7 +1,20 @@
...
+
+  private audioBuffer: AudioBuffer | null;
+  private source: AudioBufferSourceNode | null;
+  private playbackRate: number;
+  private target?: AudioNode;
+
+  private _markDone?: () => void;
+  private _doneDownloading?: (fromMoreRecentCall: boolean) => void;
+
+  private static _audioContext: AudioContext | undefined;
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Sound.ts:16]: Good catch. In the future I'd like to use `?:` to mean "may not be initialized" and `| undefined` to mean "may be set or unset at any given time".

File: src/Sound.ts [hunk 33]
```diff
@@ -51,7 +64,7 @@ export default class Sound {
       // finish playing. Of course, the latest call returns true, and so the
       // containing playUntilDone() (if present) knows to wait.
       const oldDoneDownloading = this._doneDownloading;
-      this._doneDownloading = fromMoreRecentCall => {
+      this._doneDownloading = (fromMoreRecentCall): void => {
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Sound.ts:67]: It can infer the type because it's defined on the class field.

File: src/Sound.ts [hunk 34]
```diff
@@ -174,44 +192,158 @@ export default class Sound {
...
+// The order of this array matches AudioEngine's effects list in scratch-audio.
+// Earlier in the list is closer to the EffectChain input node; later is closer
+// to its target (output). Note that a non-"patch" effect's position in the
+// array has no bearing on effect behavior, since it isn't part of the chain
+// system.
+//
+// Note that this descriptor list is fairly easy to build on, if we'd like to
+// add more audio effects in the future. (Scratch used to have more, but they
+// were removed - see commit ff6cd4a - because they depended on an external
+// library and were too processor-intensive to support on some devices.)
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Sound.ts:244]: Whitespace has been tweaked.

File: src/Sound.ts [hunk 35]
```diff
@@ -526,130 +696,76 @@ export class EffectChain {
...
+  ) => void;
+} & EffectDescriptorBase<Name>;
+
+type EffectDescriptor<
+  isPatch extends boolean,
+  Name extends string,
+  Nodes extends isPatch extends true ? object : never
+> = isPatch extends true
+  ? PatchDescriptor<Name, Nodes>
+  : PatchlessDescriptor<Name>;
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Sound.ts:737]: Moved upwards below the comment.

File: src/Sound.ts [hunk 36]
```diff
@@ -174,44 +192,158 @@ export default class Sound {
...
+  },
+  set(value, { node }) {
+    node.gain.linearRampToValueAtTime(
+      value / 100,
+      Sound.audioContext.currentTime + EffectChain.decayDuration
+    );
+  },
+} as const;
+
+const effectDescriptors = [PanEffect, PitchEffect, VolumeEffect] as const;
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Sound.ts:320]: It's allowing us to get the complete list of effect descriptors at compile-time. It allows it to type as `[PatchDescriptor<...>, PatchlessDescriptor<...>, PatchDescriptor<...>]` with each specific type parameter filled in completely. Without the `as const`, it would type as an array of a union of all three.

File: src/Sound.ts [hunk 37]
```diff
@@ -174,44 +192,158 @@ export default class Sound {
...
 export class EffectChain {
   // The code in this class is functionally comparable to the class of the same
   // name in the scratch-audio library, but is completely rewritten and follows
   // somewhat different logic. Still, the class exists on the same principle:
   // a portable way to store the effect chain, independent of the audio sources
   // it affects.
 
-  constructor(config) {
+  // TODO: stop storing config; we just use getNonPatchSoundList directly
+  private config: EffectChainConfig;
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Sound.ts:333]: Removed it.

File: src/Sound.ts [hunk 38]
```diff
@@ -174,44 +192,158 @@ export default class Sound {
...
+  public inputNode: AudioNode;
+  private getNonPatchSoundList: () => Sound[];
+  private effectValues!: Record<EffectName, number>;
+  private effectNodes: {
+    [T in typeof effectDescriptors[number] as T["name"]]?: ReturnType<
+      // We need to infer this type here, I think
+      // eslint-disable-next-line @typescript-eslint/no-unused-vars
+      T extends PatchDescriptor<string, infer _V> ? T["makeNodes"] : never
+    >;
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Sound.ts:342]: It turns out we don't need the `infer _V`; we can just replace it with `any`

File: src/Trigger.ts [hunk 39]
```diff
@@ -0,0 +1,125 @@
+import type { Sprite, Stage } from "./Sprite";
+
+const GREEN_FLAG = Symbol("GREEN_FLAG");
+const KEY_PRESSED = Symbol("KEY_PRESSED");
+const BROADCAST = Symbol("BROADCAST");
+const CLICKED = Symbol("CLICKED");
+const CLONE_START = Symbol("CLONE_START");
+const LOUDNESS_GREATER_THAN = Symbol("LOUDNESS_GREATER_THAN");
+const TIMER_GREATER_THAN = Symbol("TIMER_GREATER_THAN");
+const BACKDROP_CHANGED = Symbol("BACKDROP_CHANGED");
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Trigger.ts:10]: Moved them onto the static properties of `Trigger`.

File: src/Sound.ts [hunk 40]
```diff
@@ -321,10 +462,10 @@ export class EffectChain {
       // node as both its input and output.) Other effects are more complex.
       // The code in this block controls the actual chaining behavior of
       // EffectChain, assuring that all effects form a clean chain.
-      let nodes = this.effectNodes[descriptor.name];
+      let nodes = this.effectNodes[descriptor.name]!;
       if (!nodes && value !== descriptor.initial) {
         nodes = descriptor.makeNodes();
-        this.effectNodes[descriptor.name] = nodes;
+        this.effectNodes[descriptor.name] = nodes as never;
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Sound.ts:468]: Fixed it to make it more obvious what's actually going on

File: src/Sprite.ts [hunk 41]
```diff
@@ -150,68 +221,53 @@ class SpriteBase {
...
+  public warp(procedure: GeneratorFunction): (...args: unknown[]) => void {
     const bound = procedure.bind(this);
     return (...args) => {
       const inst = bound(...args);
       while (!inst.next().done);
     };
   }
 
-  random(a, b) {
+  // TODO: this should also take strings so rand("0.0", "1.0") returns a random float like Scratch
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Sprite.ts:269]: https://github.com/leopard-js/leopard/issues/167

File: src/Sprite.ts [hunk 42]
```diff
@@ -294,38 +350,38 @@ class SpriteBase {
...
+  public clearPen(): void {
     this._project.renderer.clearPen();
   }
 
-  *askAndWait(question) {
-    if (this._speechBubble) {
+  public *askAndWait(question: string): Yielding<void> {
+    if (this._speechBubble && this instanceof Sprite) {
       this.say("");
     }
```
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Sprite.ts:360]: Good catch! Fixed.

File: src/Sprite.ts (hunk 10 above)
Comment (adroitwhiz) [reply src/Sprite.ts:567]: Actually, it looks like `this.clones` only contains direct clones. A clone of a clone of a clone(...) is not included in it.

File: src/Sprite.ts (hunk 11 above)
Comment (adroitwhiz) [reply src/Sprite.ts:639]: Good catch! Fixed the argument type.

File: src/Sprite.ts (hunk 13 above)
Comment (adroitwhiz) [reply src/Sprite.ts:773]: After pondering this for a bit, I've come to the conclusion that this code has actually just been subtly broken the whole time. If another thread comes along and clears the speech bubble timeout, the `done` flag will never be set and we'll be stuck waiting forever.

Let's just rewrite this entirely in another PR.

File: src/Sprite.ts (hunk 14 above)
Comment (adroitwhiz) [reply src/Sprite.ts:701]: Yes, and there's no real point in having it since it's redundant with the class name.

File: src/renderer/Skin.ts (hunk 15 above)
Comment (adroitwhiz) [reply src/renderer/Skin.ts:17]: I've documented the function a bit better.

File: src/renderer/SpeechBubbleSkin.ts (hunk 16 above)
Comment (adroitwhiz) [reply src/renderer/SpeechBubbleSkin.ts:51]: The type annotation can be inferred only if there's a corresponding getter. In this case there wasn't; I'll add one.

File: src/renderer/SpeechBubbleSkin.ts (hunk 17 above)
Comment (adroitwhiz) [reply src/renderer/SpeechBubbleSkin.ts:66]: Making it an enum would be a breaking change, I think. I've exported the type as a union.

File: src/renderer/Drawable.ts (hunk 18 above)
Comment (adroitwhiz) [reply src/renderer/Drawable.ts:36]: I think I added them then realized the properties could be undefined. I've removed them now.

File: src/Watcher.ts (hunk 19 above)
Comment (adroitwhiz) [reply src/Watcher.ts:82]: Good catch! Removed these.

File: src/Watcher.ts (hunk 21 above)
Comment (adroitwhiz) [reply src/Watcher.ts:162]: https://github.com/leopard-js/leopard/issues/168

File: src/Renderer.ts (hunk 25 above)
[the remark this answers is not in the document]
Comment (towerofnix) [reply src/Renderer.ts:297]: I'm not 100% sure what I was getting at when I wrote this comment lmao, sorry.

But my (current) understanding is that `filter` isn't actually used outside of `_renderLayers` - hence its type definition there rather than on `RenderSpriteOptions`. So the `options` object we end up passing along, which is defined here... ends up being a full `RenderSpriteOptions` *with extra* options from `optionsIn` (i.e. `filter`), which inevitably goes unused.

We still need an options input to pass it to `renderSprite` and to access or provide `drawMode`. But the only reason *for* destructure `filter` from it is for legibility, when calling `_renderLayers`; and this way gives us a complicated type definition `{ filter?: ... } & ...` and we end up passing along a completely unused `filter` option in an object where it doesn't fit (`RenderSpriteOptions`).

(We don't ever destructure anything except the `filter` option, but we need to keep `renderSpeechBubbles: true` in the `options` variable because it's serving as a default, the value unless specifically overridden by `optionsIn`. Removing it would be a behavior change, defaulting to undefined instead of true.)

My rewrite would be the `_renderLayers` definition I wrote above, but with `options` renamed to `optionsIn` like you have it, and then:

```js
private _renderLayers(...): void {
  // IFF there's no cleaner way to provide defaults for drawMode
  // and renderSpeechBubbles directly in parameters
  const options = {
    drawMode: ShaderManager.DrawModes.DEFAULT,
    renderSpeechBubbles: true,
    ...optionsIn;
  };

  const shouldRestrictLayers = layers instanceof Set;
  const shouldIncludeLayer = (layer: Sprite | Stage | PenSkin): boolean =>
    !(
      // just access filter as-is instead of from options
      (shouldRestrictLayers && !layers.has(layer)) ||
      (filter && !filter(layer))
    );
  ...
}
```

File: src/Sprite.ts [hunk 43]
```diff
@@ -30,31 +58,64 @@ class _EffectMap {
...
             this._bitmask = this._bitmask | (1 << i);
           }
-        }
+        },
       });
     }
   }
 
-  _clone() {
+  public _clone(): _EffectMap {
```
[the remark this answers is not in the document]
Comment (towerofnix) [reply src/Sprite.ts:66]: I think there's potential to rework this and avoid exposing it publicly (= privatize it and drop the underscore for consistency), but let's save that for later.

File: src/Sprite.ts (hunk 9 above)
Comment (towerofnix) [reply src/Sprite.ts:584]: Branched to #166.

File: src/Sprite.ts (hunk 12 above)
Comment (towerofnix) [reply src/Sprite.ts:757]: Branched into #169

File: src/Sprite.ts (hunk 13 above)
Comment (towerofnix) [reply src/Sprite.ts:844]: Branched to #170.

File: src/renderer/SpeechBubbleSkin.ts (hunk 17 above)
Comment (towerofnix) [reply src/renderer/SpeechBubbleSkin.ts]: Thanks, yeah, I've put it into a separate slightly broader issue with other similar breaking changes: #169

**Review by towerofnix — CHANGES_REQUESTED** [review]
Tested this out locally with...

* [Colorlens](https://scratch.mit.edu/projects/568839795/) by yuski347 to confirm overall behavior correctness (complex project which is 98% functioning - both before and after this PR!)
* [Audio effects demo](https://scratch.mit.edu/projects/363195646/) by me to confirm audio effects are still working (yep!)

I've requested one change but otherwise this is LGTM! 🎉

I think it'd be a good idea to start putting together a "project corpus" as a list of projects, preferably some complex ones included, demonstrating various behaviors which are currently functioning in Leopard, which we can test new larger pull requests like this one against.

File: src/Renderer.ts (hunk 25 above)
[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:295]: I've updated the code to pass `filter` separately.

[the remark this answers is not in the document]
Comment (towerofnix) [reply src/Renderer.ts:295]: I think this is still a behavior change? `renderSpeechBubble`, provided to following `renderSprite` calls via `options`, is defaulting to undefined instead of true in your current code.

[the remark this answers is not in the document]
Comment (adroitwhiz) [reply src/Renderer.ts:295]: I've changed `renderSprite` to only skip rendering speech bubbles if it's explicitly set to `false`.

**Review by towerofnix — CHANGES_REQUESTED** [review]
~~See comment on [behavior change](https://github.com/leopard-js/leopard/pull/146#discussion_r1130039767)~~ + We should probably still do `this._vars = vars ?? {}` in `src/Sprites.ts` even as we're implementing leopard-js/sb-edit#109, which is a separate pull request + projects may still depend on `this.vars` existing without providing initial variable values.

**Review by towerofnix — APPROVED** [review]
LGTM!

Sorry about the `Var`/`object` shenanigans! Let's keep working out the right way forward for that in leopard-js/sb-edit#109. I think we're better off merging this into master so we have a clean commit base to work on further TODO's from.

We just made the OK to push recent changes to sb-edit and Leopard online — I think it would make sense to push that release without this PR included, just because I don't know if we've done a ton of behavior testing on the changes here yet. Most changes here are hardly semantic at all, but I'd like to move to more comprehensive project testing anyway.

My idea would be to merge this, and throughout the time before next release, pull up a bunch of Scratch projects, manually testing projects and making a list of which ones are partially or entirely broken. Then, narrow down and find which behaviors Leopard currently isn't compatible with that we might've missed, and file issues for those, trying to pick off what we can. (Thread sequencing - plus support for `stop other scripts in sprite` - is probably a big one rn, for example.)

Compatibility should be better now than it used to be, but I haven't done any extensive testing to really get a feel for where we're at, and I'd like to focus on that myself for a while (as well as continuing reviews for others' pull requests).

It'll also help spot any compatibility issues which might've snuck through in this code rework - I doubt there are many, if even any, but I want to be thorough before pushing large-scale changes to the main site. How's all that sound?

Thanks again for all your work on this pull request, and for your input on issues outside this PR, too!

**Comment by towerofnix** [comment]
Want to bump Node to 18 in this pull request, since it already covers a pretty wide range of structural shenanigans? (`.github/workflows/npm-publish.yml`)

**Comment by adroitwhiz** [comment]
Sure! I've just bumped the Node version in the workflow.

**Comment by towerofnix** [comment]
Rebased against #173 now that that's merged!

**Comment by HanClinto** [comment]
How can I best help with this?  Is more review or testing needed?

**Comment by towerofnix** [comment]
@HanClinto This is good to go, it's just pending on a review from @PullJosh. Thanks for the offer to help! If you'd like to offer an extra set of eyes, you're welcome to go over changes and leave comments/questions - if you're interested in working on Leopard's internals, it's a good opportunity to familiarize yourself with the details and code patterns introduced here!

**Comment by adroitwhiz** [comment]
@PullJosh I'm leaning towards merging this PR sometime this week to unblock future improvements. Do you want to look over it first?

**Comment by PullJosh** [comment]
@adroitwhiz Honestly, with school and life going on, I don't think I'll have time. But if you and @towerofnix both feel good, I am totally on board with merging. 👍 It's definitely a good policy to require review and approval from other contributors before merging, but I don't feel that there's any reason in particular that review needs to go through me. 🙂

**Comment by towerofnix** [comment]
👍 We dug through this PR pretty thoroughly and have been working off its code for a while too, so I'm quite confident saying it's LGTM.
