### PR TITLE
Fix stamp and "touching mouse" for hidden sprites

### LINKED ISSUE #205: Allow stamping a hidden sprite
In Scratch, a hidden sprite can still be stamped using the "stamp" pen block. In Leopard, if the sprite is hidden, the stamp doesn't appear.

_(Uncovered by "Trigonometric visualizer" https://github.com/leopard-js/leopard-mentors/discussions/8)_

### PR DESCRIPTION
**Pull request by adroitwhiz**
Resolves #205.

Instead of calling renderLayers, which will not render hidden sprites, call renderSprite directly. In addition, "touching mouse" should not early-return false if the sprite is hidden.

### CODE REVIEW

File: src/Renderer.ts [hunk 1]
```diff
@@ -828,7 +824,10 @@ export default class Renderer {
 
   public stamp(spr: Sprite | Stage): void {
     this._setFramebuffer(this._penSkin._framebufferInfo);
-    this._renderLayers(new Set([spr]), { renderSpeechBubbles: false });
+    this.renderSprite(spr, {
+      drawMode: ShaderManager.DrawModes.DEFAULT,
+      renderSpeechBubbles: false,
+    });
```
Comment (towerofnix) [inline src/Renderer.ts:830]: This looks like a nicer interface for doing what we're doing anyway! Is there a reason you're passing `drawMode`, though? It's [provided as default](https://github.com/leopard-js/leopard/blob/514aa350bd546fed88b3c95c988e9afd8faff3a9/src/Renderer.ts#L293-L296) and just this would read nicer and be a more direct change:

```diff
-    this._renderLayers(new Set([spr]), { renderSpeechBubbles: false });
+    this.renderSprite(spr, { renderSpeechBubbles: false });
```

**Review by towerofnix — APPROVED** [review]
We aren't able to give this a behavior verification personally, but the code looks great except for one question!

File: src/Renderer.ts (hunk 1 above)
Comment (adroitwhiz) [reply src/Renderer.ts]: Good call; that cleans up a lot of code
